sudo: true
dist: trusty
os:
- linux
language: node_js
node_js:
- '7'
install:
- node --version
- npm --version
- npm i
- npm run build
script:
- npm run lint
before_deploy:
- rm -rf node_modules
- npm pack
- mkdir packaged
- mv ./*.tgz packaged
- ls packaged
deploy:
  provider: s3
  region: us-east-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local-dir: packaged
  bucket: beaker-plugin-safe-app
  on:
    branch: ci-test
